let ingredients = [
    'Aceite de sésamo🛢️',
    'Aceite oliva 🛢️',
    'Aceite🛢️',
    'Acelga 🌿',
    'Agua🌊',
    'Aguacate🥑',
    'Ajo en polvo🧄',
    'Ajo🧄',
    'Alcachofa',
    'Alioli de ajo negro🧄',
    'Almejas🦪',
    'Arroz de sushi ya cocido🍚',
    'Atún',
    'Azúcar🍬',
    'Batata🥔',
    'Berenjena🍆',
    'Brecol 🥦',
    'Brócoli 🥦',
    'Cacao puro 🍫',
    'Cajún',
    'Calabacín 🌿',
    'Calabacín🍆',
    'Calabaza 🌿',
    'Cardo 🌿',
    'Cayena',
    'Cebolla 🧅',
    'Cebolla caramelizada 🌿',
    'Cebolla encurtida🧅',
    'Cebolla fresca🧅',
    'Cebolla morada🧅',
    'Cebolleta 🌿',
    'Cebollino🧅',
    'Cerdo🥩',
    'Champiñones🍄',
    'Chile 🌶️',
    'Chipirones 🦑',
    'Chipotle🌮',
    'Chocolate🍫',
    'Cilantro🌿',
    'Coco rallado🥥',
    'Coles 🌿',
    'Coles de Bruselas 🌿',
    'Coliflor 🌿',
    'Copos de chili🌶️',
    'Corvina🐟',
    'Endivia 🌿',
    'Endulzante🍬',
    'Escarola',
    'Espárrago 🌿',
    'Espárragos trigueros🌿',
    'Espinaca 🌿',
    'Espinacas baby🥗',
    'Fresas🍓',
    'Frutos Rojos🍓',
    'Gambas🦐',
    'Harina🧂',
    'Harina de arroz🧂',
    'Harina de avena🧂',
    'Harina de trigo🧂',
    'Harina de trigo sarraceno🧂',
    'Hierbabuena🌿',
    'Hierbas provenzales🌿',
    'Hinojo 🌿',
    'Huevo🥚',
    'Jalapeños🌶️',
    'Jengibre en polvo🌿',
    'Judías 🌿',
    'Ketchup🍅',
    'Langostinos🦐',
    'Leche🥛',
    'Lechuga🥬',
    'Lechugas 🌿',
    'Levadura de panadería',
    'Levadura química',
    'Lima🍋',
    'Mahonesa de chipotle',
    'Maíz 🌿',
    'Mantequilla🧈',
    'Mayonesa',
    'Manzana',
    'Merluza🐟',
    'Mostaza🌭',
    'Muslos de pavo🍗',
    'Nata cocinar 🥛',
    'Nata montada🥛',
    'Nueces🥜',
    'Obleas para gyozas🍱',
    'Palmito 🌿',
    'Pasta',
    'Patata 🥔',
    'Pepino 🥒',
    'Pepino holandés🥒',
    'Perejil🌿',
    'Pico de Gallo🐔',
    'Pimienta negra molida🧂',
    'Pimienta negra🧂',
    'Pimiento 🌶',
    'Plátano🍌',
    'Puerro 🌿',
    'Queso de cabra🧀',
    'Quesitos Caserío 🧀',
    'Queso granapadano🧀',
    'Queso mozzarella🧀',
    'Remolacha 🌿',
    'Rodajas Piña🍍',
    'Sal🧂',
    'Salchicha🥩',
    'Salchichas alemanas🌭',
    'Salsa de soja🧴',
    'Salsa🧴',
    'Sésamo',
    'Sirope de arce',
    'Ternera🥩',
    'Tomate🍅',
    'Tortillas de maíz o trigo🥯',
    'Vinagre',
    'Vinagre de arroz🧴',
    'Vinagre de manzana🧴',
    'Vinagre de Módena🧴',
    'Yogur griego🥛',
    'Zanahoria🌽',
    'Zumo de limón🍋'
]

export default ingredients;