let ingredients = [
    'Patata',
    'Lechugas',
    'Acelga',
    'Alcachofa',
    'Batata',
    'Berenjena',
    'Brócoli',
    'Brecol',
    'Calabacín',
    'Calabaza',
    'Cardo',
    'Cebolla',
    'Cebolla caramelizada',
    'Cebolleta',
    'Coles',
    'Coles de Bruselas',
    'Coliflor',
    'Endivia',
    'Tomate',
    'Zanahoria',
    'Escarola',
    'Espárrago',
    'Espinaca',
    'Hinojo',
    'Judías',
    'Maíz',
    'Palmito',
    'Pepino',
    'Pimiento',
    'Puerro',
    'Remolacha',
    'Leche',
    'Atún',
    'Salchicha',
    'Plátano',
    'Manzana',
    'Ternera',
    'Cerdo',
    'Nata montada',
    'Azúcar',
    'Sal',
    'Harina',
    'Arroz',
    'Pasta',
    'Huevos',
    'Pan',
    'Aceite de oliva',
    'Aceite de girasol',
    'Vino tinto',
    'Vino blanco',
    'Levadura',
    'Canela',
    'Naranja',
    'Limón',
    'Mantequilla'
]

export default ingredients;